name: Deploy to VPS

on:
  push:
    branches:
      - master  # Trigger saat push ke main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: CLONE_DISCORD

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build backend image
        run: |
          docker build -t lawrient/be-app:latest ./be-app
      - name: Build frontend image
        run: |
         docker build \
         --build-arg NEXT_PUBLIC_HOST_API=${{ secrets.NEXT_PUBLIC_HOST_API }} \
         --build-arg NEXT_PUBLIC_HOST_WS=${{ secrets.NEXT_PUBLIC_HOST_WS }} \
         --build-arg NEXT_PUBLIC_LIVEKIT_URL=${{ secrets.NEXT_PUBLIC_LIVEKIT_URL }} \
         -t lawrient/fe-app:latest ./fe-app

      - name: Push backend image
        run: docker push lawrient/be-app:latest

      - name: Push frontend image
        run: docker push lawrient/fe-app:latest

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy repo to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          source: "."
          target: "/home/lawrient/apps/dc-clone/"

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/lawrient/apps/dc-clone

            # Buat file .env dari secrets
            echo "ALLOW_ORIGIN=${{ secrets.ALLOW_ORIGIN }}" >> .env
            echo "APP_PORT=${{ secrets.APP_PORT }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "JWT_EXPIRE_MINUTES=${{ secrets.JWT_EXPIRE_MINUTES }}" >> .env

            echo "LIVEKIT_API_KEY=${{ secrets.LIVEKIT_API_KEY }}" >> .env
            echo "LIVEKIT_API_SECRET=${{ secrets.LIVEKIT_API_SECRET }}" >> .env
            
            echo "Pull latest image..."
            sudo docker compose pull

            echo "Restarting app..."
            sudo docker compose down
            sudo docker compose up -d

            echo "Done."
