name: Deploy to VPS

on:
  push:
    branches:
      - master  # Trigger saat push ke main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: CLONE_DISCORD

    steps:
      - name: Test secret
        run: |
          if [ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
          echo "Secret DOCKER_HUB_USERNAME is empty"
          exit 1
          else
          echo "Secret DOCKER_HUB_USERNAME is set"
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build backend image
        run: |
          docker build -t lawrient/be-app:latest ./be-app

      - name: Build frontend image
        run: |
          docker build -t lawrient/fe-app:latest ./fe-app

      - name: Push backend image
        run: docker push lawrient/be-app:latest

      - name: Push frontend image
        run: docker push lawrient/fe-app:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /home/lawrient/project/
            git clone https://github.com/RivLawrient/clone-discord.git
            docker compose pull
            # Buat file .env dari secrets
            echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "NEXT_PUBLIC_HOST_API=${{ secrets.NEXT_PUBLIC_HOST_API }}" >> .env
            echo "NEXT_PUBLIC_HOST_WS=${{ secrets.NEXT_PUBLIC_HOST_WS }}" >> .env
            echo "NEXT_PUBLIC_LIVEKIT_URL=${{ secrets.NEXT_PUBLIC_LIVEKIT_URL }}" >> .env
            
            docker run --rm --env-file .env lawrient/be-app:latest migrate up

            docker compose up -d
